### ISSUE TITLE
How to watch the status of nodes in a cluster?

### ISSUE THREAD

**Issue by dglei** [ericchiang/k8s#102]
Hello,
How to monitor the EventAdded and EventDeleted of nodes in a cluster?

**Comment by ericchiang** [comment]
https://github.com/ericchiang/k8s#get-list-watch but with a v1.Node object https://godoc.org/github.com/ericchiang/k8s/apis/core/v1#Node.

Please make sure that you're responding to the active number of nodes, and not teach individual addition or deletion though https://speakerdeck.com/thockin/edge-vs-level-triggered-logic
