### ISSUE TITLE
Is it Possible to Connect with ServiceAccount instead of KubeConfig

### ISSUE THREAD

**Issue by charlesa101** [ericchiang/k8s#104]
Is it Possible to Connect with ServiceAccount with the right RBAC permissions set instead of you using the KubeConfig?

I see the mount path for the `ServiceAccount` token and ca is hardcoded here will be good to have it in as a param

https://github.com/ericchiang/k8s/blob/cee371583a0bf61583137d7611b5a87f4d8700b9/client.go#L215

**Comment by ericchiang** [comment]
I think this is what you want:

https://godoc.org/github.com/ericchiang/k8s#NewInClusterClient
