### ISSUE TITLE
Access Service Endpoints

### ISSUE THREAD

**Issue by Oliver-Fish** [ericchiang/k8s#105]
When I use kubectl describe service I get a list of endpoint IP's

Endpoints:         10.20.0.75:9000

I am getting the services like this

```
	var services corev1.ServiceList
	if err := client.List(context.Background(), k8s.AllNamespaces, &services); err != nil {
		tr.Logger.Error(err.Error())
		return
	}
	for _, p := range services.Items {
			tr.Logger.Info(fmt.Sprintf("Name: %v IP:", p.GetMetadata().GetName()))
		}
	}

```

But I can't work out how to go about getting the pod IPs inside

Any ideas?

**Comment by ericchiang** [comment]
I think you want pod.Status.PodIP https://godoc.org/github.com/ericchiang/k8s/apis/core/v1#PodStatus

First result on Google btw :)

https://www.google.com/search?q=get+pods+ip+kubernetes&rlz=1CAZZAF_enUS819&oq=get+pods+ip+kubernetes&aqs=chrome..69i57j0l5.3558j0j4&sourceid=chrome&ie=UTF-8
