### ISSUE TITLE
Support client-go credential plugins

### ISSUE THREAD

**Issue by nlowe** [ericchiang/k8s#115]
`kubectl` (and other tools based on `client-go`) support [credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins) like [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator). However, when I interact with the API to an EKS cluster via this package, it doesn't seem to be calling `aws-iam-authenticator`. For example: Getting all pods in the default namespace:

```golang
kubernetes api: Failure 403 pods is forbidden: User "system:anonymous" cannot list pods at the cluster scope
```

**Comment by ericchiang** [comment]
Credential providers and full kubeconfig loading are out of scope for this client, which is intended for in-cluster configs.

If you'd like to parse and load it yourself, use Client.SetHeader or provide an http.Client with a custom tls.Config https://godoc.org/github.com/ericchiang/k8s#Client
