### ISSUE TITLE
Failure 406 only the following media types are accepted: application/json, application/yaml

### ISSUE THREAD

**Issue by threadproc** [ericchiang/k8s#120]
When calling `.Create` with a CRD-defined object, the client attempts to send it as protobuf-encoded message which is rejected by the Kubernetes API.

**Comment by ericchiang** [comment]
Does your CRD implement the proto Message interface? If so this client will assume it should be encoded as a protobuf.

https://godoc.org/github.com/golang/protobuf/proto#Message

**Comment by threadproc** [comment]
Taking another look at it with fresh eyes, I'm extending the `runtime.TypeMeta` type, which brings in the `Reset`, `String`, and `ProtoMessage` functions.

Thanks!
