### ISSUE TITLE
Explore OpenShift support

### ISSUE THREAD

**Issue by ericchiang** [ericchiang/k8s#29]
Notes:
* OpenShift publishes all there proto definitions here[0].
* Wire compatible?
* Must not be imported by default for users of the `k8s` package.
* Need to expose more methods on the `k8s.Client` so other packages can use it?
* Figure out testing strategy (is there a minikube equivalent?)
* What does support look like? I don't use OpenShift so it's hard for me to guarantee I'll keep it up to date. 

Potential API might look like:

```go
import (
    "github.com/ericchiang/k8s"
    "github.com/ericchiang/k8s/openshift"
)

func main() {
    // Load regular client.
    client, err := k8s.NewInClusterClient()
    if err != nil {
        // handle error
    }

    // OpenShift client is initialized using the k8s client.
    oc := openshift.NewClient(client)
    groups, err := oc.UserV1().ListGroups()
    // ...
}
```

[0] https://github.com/openshift/origin/tree/v1.5.0-alpha.2/api/protobuf-spec

**Comment by bjartek** [comment]
There is minishift or you have oc cluster up built into the client.

**Comment by ericchiang** [comment]
Closing this for now.

I think this is covered under the existing extension support (aggregated API server, CRD, etc.). Since this client supports both custom protobuf and JSON resources registered by a user that should be enough for anyone who wants to use this client with OpenShift. I don't have any plans to include third party types in this package at this time.
