### ISSUE TITLE
Export the Options interface QueryParam method and create a FieldSelector copy of LabelSelector.

### ISSUE THREAD

**Issue by hsyed** [ericchiang/k8s#37]
I am trying to use `WatchConfigMaps` to target a single named config map at the moment. I can't find any documentation on label selectors being able to target fields -- so my assumption is that this is not possible without a `fieldSelector`. I <b>have</b> to be missing something lol.

FieldSelector also provides access to the downstream API if I remember correctly. 

Also there are a lot of handy metadata name constants [here]( https://gowalker.org/k8s.io/kubernetes/pkg/api#ListOptions) bringing some of these over into one of the packages would be very useful to figure out how to construct queries. Documentation on FieldSelector usage is quite scarce.

**Comment by ericchiang** [comment]
I've been hesitant to add them because it seems like upstream is shying away from them intentionally: https://github.com/kubernetes/kubernetes/issues/15128#issuecomment-146076116

Even if it's possible to use them, I'm not sure what the support going forward looks like, and it's definitely not something every resource enables.

**Comment by hsyed** [comment]
The scarcity of documentation does indicate that. But the use case I am tackling is very standard. I'd be happy enough with another abstraction -- how about an Option type for metadata.name sets ? That does seem convoluted though.

The downstream api is very powerfull for advanced use. I can't see any harm for supporting FieldSelectors. At the end of the day it's a restfull query parameter.

**Comment by ericchiang** [comment]
> I can't see any harm for supporting FieldSelectors.

They don't work on a lot of resources and it sounds like they aren't optimized on the backend. So there could be the harm of buggy support and performance hits.

**Comment by hsyed** [comment]
OK so if that is this case does that mean there won't be support for being able to target a watch query to downstream api fields -- are these going to be available within the namespace of a LabelSelector ?The rest of the downstream api fields  do not matter to me at the moment but the ConfigMap metadata.name does. I must be missing something, is there another way to do what I am asking ?

**Comment by ericchiang** [comment]
Applying labels to your configmap seems like a reasonable solution. If not you can get the configmap in a loop or do the filtering client side.

**Comment by ericchiang** [comment]
You can use QueryParam for this now https://godoc.org/github.com/ericchiang/k8s#QueryParam
