### ISSUE TITLE
How should a watcher be terminated?

### ISSUE THREAD

**Issue by F21** [ericchiang/k8s#41]
It seems that `watcher.Next()` is blocking. I want to be able to run a watch in a goroutine and stop the watcher via a channel:

```go
func watch(watcher *k8s.CoreV1PodWatcher,  stop <-chan struct{}) {

	for {
		select {

		default:
			if event, pod, err := watcher.Next(); err != nil {
				k.logger.Errorf("Error getting next watch: %s", err)
			} else {
				// Do stuff here
			}

		case <-stop:
			watcher.Close()
			return
		}
	}
}

//run watcher in goroutine
go watch(podWatcher, stop)
```

However, since `watcher.Next()` is blocking, it is possible that the case for receiving from `stop` may never be called. Is there a way to terminate a watcher?

**Comment by ericchiang** [comment]
`watcher.Next` is actually just de-serializing from the HTTP long poll. So when `Next` fails, it indicate the watcher is dead and shouldn't be called again. Maybe I should provide better examples?

It sounds like you want to actually watch forever, handling each event as it comes in, then attempting to re-watch when the connection fails. Maybe something like this? (I haven't actually tested this)

```go
type podEvent struct {
	event *versioned.Event
	pod   *v1.Pod
}

// watchPods watches pods in the client's namespace, calling handler on each
// event received from the watch. It watches until context is canceled.
func watchPods(ctx context.Context, client *k8s.Client, handler func(e podEvent)) {
	// Last observed resource version.
	resourceVersion := ""

	// Channels used for each instance of the watch.
	eventCh := make(chan podEvent, 1)
	errCh := make(chan error, 1)
	for {
		opt := k8s.ResourceVersion(resourceVersion)

		watcher, err := client.CoreV1().WatchPods(ctx, client.Namespace, opt)
		if err != nil {
			log.Printf("watch pods: %v", err)
			// Implement backoff behavior here.
		}

		for {
			go func() {
				event, pod, err := watcher.Next()
				if err != nil {
					errCh <- err
					return
				}
				eventCh <- podEvent{event, pod}
			}()

			select {
			case e := <-eventCh:
				// Update last observed resource version.
				resourceVersion = *e.pod.Metadata.ResourceVersion
				handler(e)
			case err := <-errCh:
				log.Printf("watch err: %v", err)
				break
			case <-ctx.Done():
				watcher.Close()
				return
			}
		}
	}
}
```

**Comment by ericchiang** [comment]
I think you bring up a good point though. Watches are a little different than client-go and that should be called out in the docs.

**Comment by F21** [comment]
Hey, thanks! Your example makes a lot of sense.

It would be great if a higher level api is implemented, smilar to the one in the official k8s.io client: https://godoc.org/k8s.io/apimachinery/pkg/watch#Interface

It would then be pretty easy to use the watcher in a `for select` loop and read events over a channel.

**Comment by ericchiang** [comment]
@F21 do you know what the retry behavior for the upstream client is? I've generally avoided adding higher level APIs because:

* It's hard to inject loggers into higher level interfaces (client-go just assumes glog everwhere).
* It's hard to get it right, and hard to produce a typed interface without generating a lot more code.
* client-go already implements these interfaces.

I think I'd rather have this client provide raw API capabilities and provide examples like the one above for users who want the added features.

**Comment by F21** [comment]
@ericchiang Unfortunately, no. However, your reasoning makes a lot of sense!

**Comment by antoniomo** [comment]
> watcher.Next is actually just de-serializing from the HTTP long poll. So when Next fails, it indicate the watcher is dead and shouldn't be called again.

In the above snippet, the code:

```go
			case err := <-errCh:
				log.Printf("watch err: %v", err)
				break
```

Would just break from the select statement, causing us to restart the inner for-loop and re-using the existing watcher in a new goroutine with `watcher.Next()`, without reconnecting. Am I missing something?
