### ISSUE TITLE
Errors can sometimes be non-protobuf encoded

### ISSUE THREAD

**Issue by ericchiang** [ericchiang/k8s#46]
Reported by a user:

Client got an RBAC denial with an in-cluster client. The error returned was:

```
decode error status: payload is not a kubernetes protobuf object
```

Try to reproduce. Maybe an upstream issue?

**Comment by eicca** [comment]
I got the same problem trying the basic example with listing nodes using out of the cluster client.

- go version 1.8
- Kubernetes version 1.6.2 deployed on GKE

Unfortunately, I wasn't able to figure out what exactly is going wrong here.

**Comment by John-Lin** [comment]
same here.  basic example in-cluster client.
```
$ kc get nodes
NAME               STATUS    AGE       VERSION
k8s-ovs-master-1   Ready     27d       v1.6.5
k8s-ovs-minion-1   Ready     27d       v1.6.5
```

**Comment by ericchiang** [comment]
So I think the solution here is to either support JSON for the error status object or include the error object as a string in the error message (maybe inspect it to make sure it's utf8 first and not random bytes).

**Comment by BlueMonday** [comment]
I have also hit this error when attempting to delete a non existing pod or service (haven't tried other resource types). This is unfortunate because I would like to check the kind of error and handle the error specifically if the resource did not exist.

This is against a Kubernetes 1.7.3 cluster.

Code which reproduces the problem:

```go
package main

import (
	"context"
	"io/ioutil"
	"log"

	"github.com/ericchiang/k8s"
	"github.com/ghodss/yaml"
)

func main() {
	ctx := context.Background()

	data, err := ioutil.ReadFile("/home/serenst/.kube/config")
	if err != nil {
		log.Fatalf("Error read kubeconfig: %v", err)
	}

	var config k8s.Config
	if err := yaml.Unmarshal(data, &config); err != nil {
		log.Fatalf("Error unmarshal kubeconfig: %v", err)
	}
	client, err := k8s.NewClient(&config)
	if err != nil {
		log.Fatal(err)
	}

	err = client.CoreV1().DeletePod(ctx, "this-pod-does-not-exist", "analytics")
	if err != nil {
		log.Fatalf("%#v", err)
	}
}
```

Output:

```
2017/08/24 11:42:02 &errors.errorString{s:"decode error status: payload is not a kubernetes protobuf object"}
exit status 1
```
