### ISSUE TITLE
Delete options for cascading deletes

### ISSUE THREAD

**Issue by ericchiang** [ericchiang/k8s#51]
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#setting-the-cascading-deletion-policy

**Comment by hongshibao** [comment]
I set opitons to k8s.QueryParam("orphanDependents", "false") to do cascading deletes

**Comment by ericchiang** [comment]
I think I'm going to encourage query parameters to use `k8s.QueryParam` instead of introducing typed conveniences. Closing.
