### ISSUE TITLE
v1.ConfigMapKeySelector missing Name field

### ISSUE THREAD

**Issue by noonien** [ericchiang/k8s#53]
[v1.ConfigMapKeySelector](https://godoc.org/github.com/ericchiang/k8s/api/v1#ConfigMapKeySelector) seems to be missing the Name field, this causes the following error when dealing with pods that have envs from configmaps:

`spec.containers[0].env[3].valueFrom.configMapKeyRef.name: Required value`

**Comment by ericchiang** [comment]
When those types are generated from the protobuf definitions they don't inline the fields like the Go structs.

https://github.com/kubernetes/kubernetes/blob/v1.7.0/pkg/api/v1/types.go#L1511

So the error's a little JSON specific. You should be able to set the name value on the LocalObjectReference field.

https://godoc.org/github.com/ericchiang/k8s/api/v1#LocalObjectReference

I think that should do it. Please let me know if there are any issues and I can re-open the issue.
