### ISSUE TITLE
deployment scale subresource is registered as a top level type

### ISSUE THREAD

**Issue by 23doors** [ericchiang/k8s#54]
Dunno if it changed in 1.6 but v1beta1 GetScale etc are incorrect.
They query `v1beta1/namespaces/xxx/scales/name/`
While in 1.6 there seems to be: `v1beta/namespaces/xxx/deployment/deploy_name/scale/`

**Comment by ericchiang** [comment]
Ah, this package doesn't support subresources yet. Thanks for the note, will try to fix that when subresources are supported.

**Comment by ericchiang** [comment]
Closed via https://github.com/ericchiang/k8s/pull/84
