### ISSUE TITLE
InsecureSkipTLSVerify not implemented

### ISSUE THREAD

**Issue by sidmutha** [ericchiang/k8s#55]
In the config being passed to `k8s.NewClient`, I set the flag `InsecureSkipTLSVerify` to `true`for a particular cluster. But any request made to this cluster using the client returned by `k8s.NewClient` gives `x509: certificate signed by unknown authority`. I guess this is happening because the flag is not being respected in the library. I went through the source code and confirmed the same. Any help?

**Comment by ericchiang** [comment]
Yeah it looks like I overlooked this option. As a work around you should probably provide the CA.

Feel free to provide a PR to make this option respected.

**Comment by ericchiang** [comment]
closed via https://github.com/ericchiang/k8s/pull/56
