### ISSUE TITLE
Consider adding yaml tags on Config struct

### ISSUE THREAD

**Issue by sunshinekitty** [ericchiang/k8s#60]
Currently there are just json tags, this is not an issue with `github.com/ghodss/yaml` since it does yaml -> json before unmarshalling, but if you're not using this package you will find things don't unmarshal correctly.

**Comment by JorritSalverda** [comment]
I tested locally with the yaml tags, but with `gopkg.in/yaml.v2` it fails to unmarshal `certificate-authority-data` into a `[]byte`. So it's not as simple as just adding the tags.

With `github.com/ghodss/yaml@v1.0.0` and no yaml tags it worked fine though.

**Comment by ericchiang** [comment]
https://github.com/ericchiang/k8s/pull/71 has been merged
