### ISSUE TITLE
Watchers should allow a single resource

### ISSUE THREAD

**Issue by sigxcpu76** [ericchiang/k8s#67]
I want to watch for some resources (pods) and retrieve their IPs or change (e.g. delete/recreate). The simplest way to hook into this lifecycle is to group the pods in a Service and watch that endpoint.
Unfortunately, this library does not expose watch interface for a single resource by name. 

```client.CoreV1().WatchEndpoints``` is hard-coding the resource name as ```""``` here:

```url := c.client.urlFor("", "v1", namespace, "endpoints", "", options...)```

If I am not missing the right way to do that and it is in fact possible, can this be extended to pass the resource name in watch requests?

The equivalent HTTP API call is:

```curl -sSk -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/watch/namespaces/default/endpoints/rtpengine``` where ```rtpengine``` is the endpoint name.

**Comment by ericchiang** [comment]
The kubernetes watch API doesn't support watching a single resource. Best you can do is GET in a loop.

**Comment by sigxcpu76** [comment]
Why is this closed? I've provided the API curl command to watch a single resource which was tested before adding this issue. All is needed is that the hardcoded ```""``` needs to be a parameter for the resource name.
 There is also a fix on the broken single object watch here: https://github.com/kubernetes/kubernetes/pull/7263, so kubernetes has single object watch.
