### ISSUE TITLE
Readme example

### ISSUE THREAD

**Issue by citizenrich** [ericchiang/k8s#69]
I'm unable to follow the example in the readme and see pods in namespaces without an error 

The line that errors is 'pods, err := core.ListPods(ctx, k8s.AllNamespaces)' with 'undefined: core' and 'undefined: ctx'

This is using the latest version, with out of cluster auth, and the listing of nodes works just fine.

**Comment by ericchiang** [comment]
the readme has been updated.

**Comment by citizenrich** [comment]
thanks!
