### ISSUE TITLE
cannot decode json payload into protobuf object

### ISSUE THREAD

**Issue by hongshibao** [ericchiang/k8s#78]
I had a custom resource definition named ServiceMonitor, which was created by prometheus-operator (https://github.com/coreos/prometheus-operator). And I created struct definitions as follows:
```go
type ServiceEndpoint struct {
	Port *string `json:"port"`
}

type ServiceNamespaceSelector struct {
	MatchNames []string `json:"matchNames"`
}

type ServiceSelector struct {
	MatchLabels map[string]string `json:"matchLabels"`
}

type ServiceMonitorSpec struct {
	Endpoints         []*ServiceEndpoint        `json:"endpoints"`
	NamespaceSelector *ServiceNamespaceSelector `json:"namespaceSelector"`
	Selector          *ServiceSelector          `json:"selector"`
}

type ServiceMonitor struct {
	Metadata *k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta `json:"metadata"`
	Spec     *ServiceMonitorSpec                              `json:"spec,omitempty"`
}
```
Then I called the client Create() function, it returned an error:
**decode error status 404: cannot decode json payload into protobuf object**
How can I solve this issue?

**Comment by ericchiang** [comment]
Does ServiceMonitor implement protobug encoding? If it does this package assumes we can't naively decode into a proto object unless it implements `json.Unmarshaler`

**Comment by hongshibao** [comment]
I found the root cause. The name I registered for serivice monitor was wrong. It should be "servicemonitors", previously I set it "ServiceMonitor"
