### ISSUE TITLE
User is "system:anonymous" when using out of cluster client with GKE

### ISSUE THREAD

**Issue by oli-d-ovo** [ericchiang/k8s#79]
Using the following code to create an out of cluster client:

```
	data, err := ioutil.ReadFile(utils.HomeDir() + "/.kube/config")
	if err != nil {
		panic(err)
	}

	// Unmarshal YAML into a Kubernetes config object.
	var config k8s.Config
	if err := yaml.Unmarshal(data, &config); err != nil {
		panic(err)
	}
	client, err := k8s.NewClient(&config)
```

I am getting the following error when I try to list pods in a namespace:
```
kubernetes api: Failure 403 pods is forbidden: User "system:anonymous" cannot list pods in the namespace "ns": No policy matched.
```

(I'm also running Kubernetes on a GKE cluster)

I've confirmed that the config in use is the same as the one that `kubectl` uses. I don't have any problems running `kubectl`.

Is there something extra I need to do in order to authenticate?

As mentioned in #77, I have chosen this library in that hope that it will abstract away a lot of the lower level Kubernetes functions and allow me to easily execute some simple commands on my cluster. I've raised this as an issue as I'm unsure where else to go, but it could be an error on my part.

**Comment by ericchiang** [comment]
What does your kubeconfig look like? What version of this package are you using?

Are you using the GCP auth provider? We don't actively support that. https://github.com/kubernetes/kubernetes/blob/99295356ed152663698e002494a5af00d682dc6b/plugin/pkg/client/auth/gcp/gcp.go

**Comment by ericchiang** [comment]
@markvincze I'd recommend creating a service account, grab that token and put it in a kubeconfig. Use that kubeconfig to test your client out-of-cluster.

Or you could use kubectl to proxy the API server locally https://kubernetes.io/docs/tasks/access-kubernetes-api/http-proxy-access-api/

**Comment by markvincze** [comment]
Hi @ericchiang,

Thanks a lot for the quick reply! The `kubectl proxy` trick works nicely!

(Just for future reference for anyone finding this later: after starting `kubectl proxy` in a terminal, you have to replace the address in the `clusters/cluster/server` field in the kube config file with `http://127.0.0.1:8080`.)

Cheers,
Mark

**Comment by weeco** [comment]
Same issue here. I remember that I had to import "k8s.io/client-go/plugin/pkg/client/auth" to get the out of cluster client working on GKE using the official go client. I am not able to use this client with a GKE out of cluster communication though
