### ISSUE TITLE
Some structs should be inlined.

### ISSUE THREAD

**Issue by ewoutp** [ericchiang/k8s#8]
`LocalObjectReference` in `v1.SecretKeySelector` should have `,inline` in its json tag.
This is likely a wrong setting of protoc.

As a result, creating and `v1.EnvVar` in a container with an env variable drawn from a secret does not work.

**Comment by ericchiang** [comment]
I don't think this client is aiming for JSON serialization support. If the generated protobufs work for talking to the API server, I think that's the best we're going to get.
