### ISSUE TITLE
cannot decode json payload into protobuf object

### ISSUE THREAD

**Issue by ewoutp** [ericchiang/k8s#82]
Got the above error when trying to `Create` a custom resource.
I traced the problem to `v1.Status` not implementing `json.Unmarshaler`.

This is what happens:
- I called `Create`. Since I do not implement the protobuffer interface, it marshals to JSON
- I made a mistake in naming, so k8s returns an error in the form of a `Status` object encoded in JSON. (but this can be any normal error that k8s can return)
- The client detects the error and tries to unmarshal in `*v1.Status`.
- Since `Status` does implement the protobuffer interface but not `json.Unmarshaler`, the unmarshal function does not accept the JSON body.

The problem was gone when I excluded `*v1.Status` from the check in `unmarshal`.
```
	if isPBMsg {
		if _, ok := i.(*metav1.Status); ok {
			// only decode into JSON of a protobuf message if the type
			// explicitly implements json.Unmarshaler
			if _, ok := i.(json.Unmarshaler); !ok {
				return errors.New("cannot decode json payload into protobuf object: " + string(data) + ", " + reflect.TypeOf(i).String())
			}
		}
	}
```

**Comment by ericchiang** [comment]
Thanks for the detailed bug report!

https://github.com/ericchiang/k8s/pull/83 should fix this.
